# Generated by Django 6.0.1 on 2026-10-08 09:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('product_qty', models.CharField(blank=True, max_length=64)),
                ('unit_price', models.PositiveIntegerField()),
                ('inventory', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='product_price_positive'), models.CheckConstraint(condition=models.Q(('inventory__gte', 0)), name='product_inventory_non_negative')],
            },
        ),
    ]
