# Generated by Django 6.0.1 on 2026-10-08 10:24

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=store.models.generate_coupon_code, max_length=32, unique=True)),
                ('milestone', models.PositiveIntegerField(unique=True)),
                ('discount_percent', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('redeemed', 'Redeemed')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['milestone'],
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_percent__gte', 1), ('discount_percent__lte', 100)), name='coupon_percent_1_100'), models.CheckConstraint(condition=models.Q(models.Q(('redeemed_at__isnull', False), ('status', 'redeemed')), models.Q(('redeemed_at__isnull', True), ('status', 'available')), _connector='OR'), name='coupon_status_redeemed_at_consistent')],
            },
        ),
    ]
