"""Administrative operations: coupon generation, coupon listing, reporting."""
from contextlib import contextmanager
from itertools import count

from django.db import IntegrityError, connection, transaction
from django.db.models import Count, Sum

from store.api_errors import ApiError
from store.models import Coupon, Order, OrderItem, Product

from .config import coupon_config


def _next_unrewarded_milestone(n, existing):
    return next(k * n for k in count(1) if k * n not in existing)


def generate_coupon():
    """Creates the LOWEST unrewarded milestone (n, 2n, 3n, ...) that has been reached.

    Coupon.milestone is UNIQUE, so even if two requests compute the same milestone at the same
    instant, the database lets exactly one INSERT win; the loser gets a 409."""
    n, percent = coupon_config()
    try:
        with transaction.atomic():
            total_orders = Order.objects.count()
            existing = set(Coupon.objects.values_list("milestone", flat=True))
            for k in range(1, total_orders // n + 1):
                if k * n not in existing:
                    return Coupon.objects.create(milestone=k * n, discount_percent=percent)
    except IntegrityError:
        raise ApiError(409, "COUPON_ALREADY_GENERATED",
                       "a coupon for this milestone was generated by a concurrent request")
    nxt = _next_unrewarded_milestone(n, existing)
    raise ApiError(409, "NO_ELIGIBLE_MILESTONE", "no unrewarded order milestone has been reached",
                   {"total_orders": total_orders, "every_n_orders": n,
                    "next_milestone": nxt, "orders_needed": max(nxt - total_orders, 0)})


def list_coupons(status=None):
    qs = Coupon.objects.select_related("order").order_by("milestone")
    return qs.filter(status=status) if status else qs


@contextmanager
def consistent_snapshot():
    """All report queries must see ONE database snapshot, otherwise an order committed between
    two queries makes the totals disagree with each other. REPEATABLE READ gives that on
    PostgreSQL. (SET TRANSACTION must be the first statement, so it is skipped when the caller is
    already inside a transaction, e.g. ATOMIC_REQUESTS=True or Django's TestCase.)"""
    with transaction.atomic():
        if connection.vendor == "postgresql" and not getattr(connection, "_report_in_outer_tx", False):
            if len(connection.savepoint_ids) == 0 and not _outer_transaction_active():
                with connection.cursor() as cursor:
                    cursor.execute("SET TRANSACTION ISOLATION LEVEL REPEATABLE READ")
        yield


def _outer_transaction_active():
    # atomic() above has just opened our transaction; if it was nested we are in a savepoint.
    return len(connection.savepoint_ids) > 0


def build_report():
    """Read-only. Every figure is derived from orders / order items / coupons in one snapshot."""
    n, percent = coupon_config()
    with consistent_snapshot():
        totals = Order.objects.aggregate(orders=Count("id"), gross=Sum("subtotal"),
                                         discounts=Sum("discount_amount"), net=Sum("total"))
        per_product = list(OrderItem.objects.values("product_id")
                           .annotate(quantity=Sum("quantity"), gross=Sum("line_total")))
        info = {p.id: p for p in Product.objects.filter(id__in=[r["product_id"] for r in per_product])}
        by_status = dict(Coupon.objects.values_list("status").annotate(c=Count("id")))
        existing = set(Coupon.objects.values_list("milestone", flat=True))

    total_orders = totals["orders"]
    available = by_status.get(Coupon.Status.AVAILABLE, 0)
    redeemed = by_status.get(Coupon.Status.REDEEMED, 0)
    pending = sum(1 for k in range(1, total_orders // n + 1) if k * n not in existing)
    rows = [{"product_id": str(r["product_id"]),
             "sku": info[r["product_id"]].sku, "name": info[r["product_id"]].name,
             "quantity": r["quantity"], "gross_revenue": r["gross"]} for r in per_product]
    return {
        "config": {"coupon_every_n_orders": n, "coupon_discount_percent": percent},
        "total_orders": total_orders,
        "gross_revenue": totals["gross"] or 0,
        "total_discounts": totals["discounts"] or 0,
        "net_revenue": totals["net"] or 0,
        "quantity_by_product": sorted(rows, key=lambda r: (r["name"], r["product_id"])),
        "coupons": {"generated": available + redeemed, "available": available,
                    "redeemed": redeemed, "pending_milestones": pending},
    }