name: Uniblox CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: ecom
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U checkout"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    env:
      DJANGO_SETTINGS_MODULE: assignment_uniblox.settings
      DB_NAME: ecom
      DB_USER: postgres
      DB_PASSWORD: root
      DB_HOST: 127.0.0.1
      DB_PORT: "5432"
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check models have migrations
        run: python manage.py makemigrations --check --dry-run

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: pytest -v